
const KEY="tm_v3_data";
let data=JSON.parse(localStorage.getItem(KEY)||'{"orgs":[],"active":null}');
let tab="resumen";
const navItems=[["resumen","📊","Resumen"],["integrantes","👥","Integrantes"],["movimientos","💳","Movimientos"],["cuotas","🧾","Cuotas"],["informes","📋","Informes"],["config","⚙️","Config"]];

function save(){localStorage.setItem(KEY,JSON.stringify(data));render()}
function org(){return data.orgs.find(o=>o.id===data.active)}
function money(n){return new Intl.NumberFormat("es-CL",{style:"currency",currency:"CLP",maximumFractionDigits:0}).format(Number(n)||0)}
function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function uid(p="id"){return p+"_"+Date.now().toString(36)+"_"+Math.random().toString(36).slice(2,7)}
function orgPick(){return data.orgs.map(o=>`<option value="${o.id}" ${o.id===data.active?"selected":""}>${esc(o.name)} · ${esc(o.year)}</option>`).join("")}
function renderNav(){document.getElementById("nav").innerHTML=navItems.map(([k,i,t])=>`<button class="${tab===k?"active":""}" onclick="tab='${k}';render()">${i} ${t}</button>`).join("")}
function render(){renderNav();const o=org();document.getElementById("orgHeader").textContent=o?`${o.name} · ${o.year}${o.rut?" · RUT "+o.rut:""}`:"Suite limpia · sin datos precargados";document.getElementById("app").innerHTML=o?views[tab](o):emptyStart()}
function emptyStart(){return `<section class="hero"><h1>Resumen de tesorería</h1><p>Visión general de aportes, movimientos, responsables y saldos.</p></section><div class="notice"><h2>Primero crea una organización.</h2><p>La aplicación comienza completamente vacía. Luego podrás registrar integrantes, cuentas, cuotas, ingresos, egresos, respaldos e informes.</p><button class="btn primary" onclick="openOrg()">+ Crear organización</button></div>`}
function empty(msg){return `<div class="empty">${msg}</div>`}

function resumen(o){
 const inc=o.mov.filter(x=>x.type==="ingreso").reduce((a,x)=>a+Number(x.amount),0), eg=o.mov.filter(x=>x.type==="egreso").reduce((a,x)=>a+Number(x.amount),0);
 const pending=o.members.reduce((a,m)=>a+(o.dues.filter(d=>d.memberId===m.id).reduce((s,d)=>s+Number(d.amount)-Number(d.paid||0),0)),0);
 return `<section class="hero"><h1>Resumen de tesorería</h1><p>Visión general de aportes, movimientos, responsables y saldos.</p><span class="pill">${esc(o.period||"Año "+o.year)}</span></section>
 <div class="grid">
 <div class="stat"><div class="label">Saldo teórico / pendiente</div><b>${money(inc-eg+pending)}</b><span class="small">Ingresos − egresos + pendientes.</span></div>
 <div class="stat"><div class="label">Saldo real · tesorero</div><b>${money(inc-eg)}</b><span class="small">Dinero efectivamente registrado en caja/cuentas.</span></div>
 <div class="stat"><div class="label">Ingresos</div><b>${money(inc)}</b><span class="small">${o.mov.filter(x=>x.type==="ingreso").length} movimientos.</span></div>
 <div class="stat"><div class="label">Egresos</div><b>${money(eg)}</b><span class="small">${o.mov.filter(x=>x.type==="egreso").length} movimientos.</span></div>
 <div class="stat"><div class="label">Pendiente de cuotas</div><b>${money(pending)}</b><span class="small">Según cuotas registradas.</span></div>
 <div class="stat"><div class="label">Integrantes</div><b>${o.members.length}</b><span class="small">Personas registradas.</span></div>
 </div>
 <div class="card"><h2>Acciones rápidas</h2><div class="btnrow"><button class="btn orange" onclick="openMember()">+ Integrante</button><button class="btn primary" onclick="openMove('ingreso')">+ Ingreso</button><button class="btn danger" onclick="openMove('egreso')">+ Egreso</button><button class="btn light" onclick="openDue()">+ Cuota / aporte</button></div></div>`;
}

function integrantes(o){
 return `<section class="hero"><h1>Integrantes</h1><p>Personas, roles, contacto, datos bancarios y estado de sus cuotas.</p><button class="btn primary" onclick="openMember()">+ Nuevo integrante</button></section>
 <div class="card scroll">${o.members.length?`<table><thead><tr><th>Nombre</th><th>RUT</th><th>Rol</th><th>Contacto</th><th>Banco / cuenta</th><th>Estado</th><th></th></tr></thead><tbody>${o.members.map(m=>`<tr><td><b>${esc(m.name)}</b><br><span class="small">${esc(m.email)}</span></td><td>${esc(m.rut)}</td><td>${esc(m.role)}</td><td>${esc(m.phone)}</td><td>${esc(m.bank)}<br>${esc(m.account)}</td><td>${m.active?"Activo":"Inactivo"}</td><td><button class="btn light" onclick="editMember('${m.id}')">Editar</button></td></tr>`).join("")}</tbody></table>`:empty("No hay integrantes registrados.")}</div>`;
}

function movimientos(o){
 const rows=o.mov.slice().sort((a,b)=>b.date.localeCompare(a.date));
 return `<section class="hero"><h1>Ingresos y egresos</h1><p>Registro separado, con responsable, categoría, medio de pago y respaldo.</p><div class="btnrow"><button class="btn primary" onclick="openMove('ingreso')">+ Registrar ingreso</button><button class="btn danger" onclick="openMove('egreso')">+ Registrar egreso</button></div></section>
 <div class="card"><div class="formgrid"><label>Organización<select onchange="data.active=this.value;save()">${orgPick()}</select></label><label>Filtrar tipo<select id="filterType" onchange="render()"><option value="">Todos</option><option value="ingreso">Ingresos</option><option value="egreso">Egresos</option></select></label></div></div>
 <div class="card scroll">${rows.length?`<table><thead><tr><th>Fecha</th><th>Tipo</th><th>Categoría</th><th>Responsable</th><th>Detalle</th><th>Monto</th><th></th></tr></thead><tbody>${rows.filter(x=>!(document.getElementById("filterType")?.value)||x.type===document.getElementById("filterType")?.value).map(x=>`<tr><td>${esc(x.date)}</td><td>${x.type==="ingreso"?"<span class='pill'>INGRESO</span>":"<span class='pill'>EGRESO</span>"}</td><td>${esc(x.category)}</td><td>${esc(x.responsible)}</td><td>${esc(x.detail)}${x.proof?"<br>📎 Respaldo adjunto":""}</td><td><b>${money(x.amount)}</b></td><td><button class="btn light" onclick="editMove('${x.id}')">Editar</button></td></tr>`).join("")}</tbody></table>`:empty("No hay movimientos registrados.")}</div>`;
}

function cuotas(o){
 const due=o.dues.slice().sort((a,b)=>a.dueDate.localeCompare(b.dueDate));
 return `<section class="hero"><h1>Cuotas y aportes</h1><p>Permite cuotas mensuales, anuales, extraordinarias y otros aportes.</p><button class="btn primary" onclick="openDue()">+ Nueva cuota / aporte</button></section>
 <div class="card scroll">${due.length?`<table><thead><tr><th>Fecha</th><th>Integrante</th><th>Tipo</th><th>Período</th><th>Exigido</th><th>Pagado</th><th>Pendiente</th></tr></thead><tbody>${due.map(d=>{let m=o.members.find(x=>x.id===d.memberId);let p=Number(d.paid||0),a=Number(d.amount);return `<tr><td>${esc(d.dueDate)}</td><td>${esc(m?.name||"—")}</td><td>${esc(d.kind)}</td><td>${esc(d.period)}</td><td>${money(a)}</td><td>${money(p)}</td><td><b>${money(Math.max(0,a-p))}</b></td></tr>`}).join("")}</tbody></table>`:empty("No hay cuotas. Puedes registrar cuotas anuales, mensuales, extraordinarias u otros aportes.")}</div>`;
}

function informes(o){
 const inc=o.mov.filter(x=>x.type==="ingreso"), eg=o.mov.filter(x=>x.type==="egreso");
 const totalI=inc.reduce((a,x)=>a+Number(x.amount),0),totalE=eg.reduce((a,x)=>a+Number(x.amount),0);
 return `<section class="hero"><h1>Informes</h1><p>Informes claros, imprimibles y exportables. Usa “Guardar como PDF” en el diálogo de impresión.</p><div class="btnrow"><button class="btn primary" onclick="printReport('general')">📄 Resumen general PDF</button><button class="btn light" onclick="downloadCSV()">⬇ Excel/CSV</button><button class="btn light" onclick="printReport('mov')">📄 Detalle movimientos</button></div></section>
 <div id="reportArea" class="card"><h2>${esc(o.name)} · Resumen general</h2><p>RUT: ${esc(o.rut||"No informado")} · Período: ${esc(o.period||o.year)}</p><div class="grid"><div class="stat"><div class="label">Total ingresos</div><b>${money(totalI)}</b></div><div class="stat"><div class="label">Total egresos</div><b>${money(totalE)}</b></div><div class="stat"><div class="label">Saldo</div><b>${money(totalI-totalE)}</b></div></div>
 <h3>Todos los ingresos</h3>${inc.length?`<table><thead><tr><th>Fecha</th><th>Categoría</th><th>Responsable</th><th>Detalle</th><th>Monto</th></tr></thead><tbody>${inc.map(x=>`<tr><td>${esc(x.date)}</td><td>${esc(x.category)}</td><td>${esc(x.responsible)}</td><td>${esc(x.detail)}</td><td>${money(x.amount)}</td></tr>`).join("")}</tbody></table>`:empty("Sin ingresos")}
 <h3>Todos los egresos</h3>${eg.length?`<table><thead><tr><th>Fecha</th><th>Categoría</th><th>Responsable</th><th>Detalle</th><th>Monto</th></tr></thead><tbody>${eg.map(x=>`<tr><td>${esc(x.date)}</td><td>${esc(x.category)}</td><td>${esc(x.responsible)}</td><td>${esc(x.detail)}</td><td>${money(x.amount)}</td></tr>`).join("")}</tbody></table>`:empty("Sin egresos")}</div>`;
}

function config(o){
 return `<section class="hero"><h1>Configuración</h1><p>Datos de la organización, representantes, respaldos y seguridad.</p></section>
 <div class="card"><h2>Organización</h2><div class="formgrid"><label>Nombre<input id="oname" value="${esc(o.name)}"></label><label>RUT<input id="orut" value="${esc(o.rut)}" placeholder="Ej. 65.123.456-7"></label><label>Año<input id="oyear" value="${esc(o.year)}" type="number"></label><label>Período<input id="operiod" value="${esc(o.period||"Marzo-Diciembre")}"></label><label>Dirección<input id="oaddress" value="${esc(o.address)}"></label><label>Ciudad / comuna<input id="ocity" value="${esc(o.city)}"></label><label>Teléfono<input id="ophone" value="${esc(o.phone)}"></label><label>Página web<input id="oweb" value="${esc(o.web)}"></label><label>Instagram<input id="oinsta" value="${esc(o.instagram)}"></label><label>Correo<input id="oemail" value="${esc(o.email)}"></label></div><label>Descripción<textarea id="odesc">${esc(o.desc)}</textarea><div class="btnrow"><button class="btn primary" onclick="updateOrg()">Guardar datos</button><button class="btn light" onclick="exportJSON()">Exportar respaldo JSON</button><button class="btn light" onclick="document.getElementById('file').click()">Importar JSON</button><input id="file" type="file" accept=".json" hidden onchange="importJSON(this)"></div></div>
 <div class="card"><h2>Representantes</h2><button class="btn primary" onclick="openRep()">+ Agregar representante</button><div class="scroll">${o.reps.length?`<table><thead><tr><th>Nombre</th><th>RUT</th><th>Cargo</th><th>Contacto</th><th></th></tr></thead><tbody>${o.reps.map(r=>`<tr><td>${esc(r.name)}</td><td>${esc(r.rut)}</td><td>${esc(r.role)}</td><td>${esc(r.phone)} ${esc(r.email)}</td><td><button class="btn light" onclick="editRep('${r.id}')">Editar</button></td></tr>`).join("")}</tbody></table>`:empty("No hay representantes registrados.")}</div></div>
 <div class="card"><h2>Organizaciones</h2><select onchange="data.active=this.value;save()">${orgPick()}</select> <button class="btn danger" onclick="deleteOrg()">Eliminar organización</button></div>`;
}

const views={resumen:resumen,integrantes, movimientos, cuotas, informes, config};

function modal(title,body){document.getElementById("sheet").innerHTML=`<div class="btnrow" style="justify-content:space-between"><h2>${title}</h2><button class="btn light" onclick="closeModal()">✕</button></div>${body}`;document.getElementById("modal").classList.add("open")}
function closeModal(){document.getElementById("modal").classList.remove("open")}
function openOrg(){
 modal("Nueva organización",`<div class="formgrid"><label>Nombre*<input id="f_name"></label><label>RUT<input id="f_rut" placeholder="65.123.456-7"></label><label>Año<input id="f_year" type="number" value="${new Date().getFullYear()}"></label><label>Período<input id="f_period" value="Marzo-Diciembre"></label><label>Dirección<input id="f_address"></label><label>Comuna / ciudad<input id="f_city"></label><label>Teléfono<input id="f_phone"></label><label>Página web<input id="f_web"></label><label>Instagram<input id="f_instagram"></label><label>Correo<input id="f_email"></label></div><div class="btnrow"><button class="btn primary" onclick="createOrg()">Guardar organización</button></div>`)
}
function createOrg(){let name=f("f_name");if(!name)return alert("El nombre de la organización es obligatorio.");let o={id:uid("org"),name,rut:f("f_rut"),year:f("f_year"),period:f("f_period"),address:f("f_address"),city:f("f_city"),phone:f("f_phone"),web:f("f_web"),instagram:f("f_instagram"),email:f("f_email"),desc:"",members:[],mov:[],dues:[],reps:[]};data.orgs.push(o);data.active=o.id;save();closeModal()}
function f(id){return document.getElementById(id)?.value.trim()||""}
function updateOrg(){let o=org();Object.assign(o,{name:f("oname"),rut:f("orut"),year:f("oyear"),period:f("operiod"),address:f("oaddress"),city:f("ocity"),phone:f("ophone"),web:f("oweb"),instagram:f("oinsta"),email:f("oemail"),desc:f("odesc")});save();alert("Datos guardados.")}
function openMember(id=null){let m=id?org().members.find(x=>x.id===id):{};modal(id?"Editar integrante":"Nuevo integrante",`<div class="formgrid"><label>Nombre completo*<input id="m_name" value="${esc(m.name)}"></label><label>RUT<input id="m_rut" value="${esc(m.rut)}"></label><label>Rol<input id="m_role" value="${esc(m.role)}" placeholder="Alumno, apoderado, socio..."></label><label>Teléfono<input id="m_phone" value="${esc(m.phone)}"></label><label>Correo<input id="m_email" value="${esc(m.email)}"></label><label>Banco<input id="m_bank" value="${esc(m.bank)}"></label><label>Tipo de cuenta<input id="m_accountType" value="${esc(m.accountType)}"></label><label>Número de cuenta<input id="m_account" value="${esc(m.account)}"></label></div><label><input id="m_active" type="checkbox" ${m.active!==false?"checked":""}> Integrante activo</label><div class="btnrow"><button class="btn primary" onclick="saveMember('${id||""}')">Guardar</button></div>`)}
function editMember(id){openMember(id)}
function saveMember(id){let o=org(),m=id?o.members.find(x=>x.id===id):{id:uid("mem")};Object.assign(m,{name:f("m_name"),rut:f("m_rut"),role:f("m_role"),phone:f("m_phone"),email:f("m_email"),bank:f("m_bank"),accountType:f("m_accountType"),account:f("m_account"),active:document.getElementById("m_active").checked});if(!m.name)return alert("Nombre obligatorio.");if(!id)o.members.push(m);save();closeModal()}
function memberOptions(){return org().members.map(m=>`<option value="${m.id}">${esc(m.name)}</option>`).join("")}
function openMove(type="ingreso",id=null){let x=id?org().mov.find(z=>z.id===id):{};modal(type==="ingreso"?"Registrar ingreso":"Registrar egreso",`<div class="formgrid"><label>Fecha*<input id="x_date" type="date" value="${esc(x.date||new Date().toISOString().slice(0,10))}"></label><label>Monto*<input id="x_amount" type="number" min="0" value="${esc(x.amount||"")}"></label><label>Categoría<select id="x_category">${["Cuota","Aporte extraordinario","Donación","Subvención","Venta","Transferencia","Arriendo","Compra","Servicio","Actividad","Otro"].map(v=>`<option ${x.category===v?"selected":""}>${v}</option>`).join("")}</select></label><label>Responsable<input id="x_resp" value="${esc(x.responsible||"")}"></label><label>Medio de pago<select id="x_method">${["Efectivo","Transferencia","Tarjeta","Cheque","Otro"].map(v=>`<option ${x.method===v?"selected":""}>${v}</option>`).join("")}</select></label></div><label>Detalle<textarea id="x_detail">${esc(x.detail)}</textarea></label><label>Referencia / comprobante<input id="x_proof" value="${esc(x.proof)}" placeholder="Nombre o número del comprobante"></label><div class="btnrow"><button class="btn ${type==="ingreso"?"primary":"danger"}" onclick="saveMove('${type}','${id||""}')">Guardar ${type}</button></div>`)}
function editMove(id){let x=org().mov.find(z=>z.id===id);openMove(x.type,id)}
function saveMove(type,id){let o=org(),x=id?o.mov.find(z=>z.id===id):{id:uid("mov")};Object.assign(x,{type,date:f("x_date"),amount:Number(f("x_amount")),category:f("x_category"),responsible:f("x_resp"),method:f("x_method"),detail:f("x_detail"),proof:f("x_proof")});if(!x.amount||!x.date)return alert("Fecha y monto son obligatorios.");if(!id)o.mov.push(x);save();closeModal()}
function openDue(id=null){let d=id?org().dues.find(z=>z.id===id):{};modal("Cuota / aporte",`<div class="formgrid"><label>Integrante*<select id="d_member">${memberOptions()}</select></label><label>Tipo<select id="d_kind">${["Cuota mensual","Cuota anual","Cuota extraordinaria","Aporte voluntario","Otro"].map(v=>`<option ${d.kind===v?"selected":""}>${v}</option>`).join("")}</select></label><label>Período<input id="d_period" value="${esc(d.period||new Date().getFullYear())}"></label><label>Vencimiento<input id="d_date" type="date" value="${esc(d.dueDate||new Date().toISOString().slice(0,10))}"></label><label>Monto exigido<input id="d_amount" type="number" value="${esc(d.amount||"")}"></label><label>Pagado<input id="d_paid" type="number" value="${esc(d.paid||0)}"></label></div><div class="btnrow"><button class="btn primary" onclick="saveDue('${id||""}')">Guardar cuota</button></div>`)}
function saveDue(id){let o=org(),d=id?o.dues.find(z=>z.id===id):{id:uid("due")};Object.assign(d,{memberId:f("d_member"),kind:f("d_kind"),period:f("d_period"),dueDate:f("d_date"),amount:Number(f("d_amount")),paid:Number(f("d_paid"))});if(!d.memberId||!d.amount)return alert("Integrante y monto son obligatorios.");if(!id)o.dues.push(d);save();closeModal()}
function openRep(id=null){let r=id?org().reps.find(x=>x.id===id):{};modal("Representante",`<div class="formgrid"><label>Nombre*<input id="r_name" value="${esc(r.name)}"></label><label>RUT<input id="r_rut" value="${esc(r.rut)}"></label><label>Cargo<input id="r_role" value="${esc(r.role)}" placeholder="Presidente, tesorero..."></label><label>Teléfono<input id="r_phone" value="${esc(r.phone)}"></label><label>Correo<input id="r_email" value="${esc(r.email)}"></label></div><div class="btnrow"><button class="btn primary" onclick="saveRep('${id||""}')">Guardar</button></div>`)}
function editRep(id){openRep(id)}
function saveRep(id){let o=org(),r=id?o.reps.find(x=>x.id===id):{id:uid("rep")};Object.assign(r,{name:f("r_name"),rut:f("r_rut"),role:f("r_role"),phone:f("r_phone"),email:f("r_email")});if(!r.name)return alert("Nombre obligatorio.");if(!id)o.reps.push(r);save();closeModal()}
function deleteOrg(){if(!confirm("¿Eliminar esta organización y todos sus datos?"))return;data.orgs=data.orgs.filter(x=>x.id!==data.active);data.active=data.orgs[0]?.id||null;save()}
function exportJSON(){let blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="tesoreria-respaldo.json";a.click();URL.revokeObjectURL(a.href)}
function importJSON(input){let file=input.files[0];if(!file)return;let r=new FileReader();r.onload=()=>{try{let x=JSON.parse(r.result);if(!x.orgs)throw Error();data=x;save();alert("Respaldo importado correctamente.")}catch(e){alert("El archivo no es un respaldo válido.")}};r.readAsText(file)}
function downloadCSV(){let o=org(),rows=[["Fecha","Tipo","Categoría","Responsable","Medio","Detalle","Monto"],...o.mov.map(x=>[x.date,x.type,x.category,x.responsible,x.method,x.detail,x.amount])];let csv=rows.map(r=>r.map(v=>`"${String(v??"").replaceAll('"','""')}"`).join(";")).join("\n"),a=document.createElement("a");a.href=URL.createObjectURL(new Blob(["\ufeff"+csv],{type:"text/csv;charset=utf-8"}));a.download=`movimientos-${o.name.replace(/\W+/g,"-")}.csv`;a.click()}
function printReport(kind){let o=org(),inc=o.mov.filter(x=>x.type==="ingreso"),eg=o.mov.filter(x=>x.type==="egreso");let rows=kind==="general"?[...inc,...eg]:o.mov;let w=window.open("","_blank");if(!w)return alert("El navegador bloqueó la ventana de impresión.");w.document.write(`<html><head><title>Informe ${esc(o.name)}</title><style>body{font-family:Arial;padding:25px;color:#182230}h1{color:#183b59}table{width:100%;border-collapse:collapse}th,td{padding:8px;border-bottom:1px solid #ddd;text-align:left}.tot{display:flex;gap:20px;margin:20px 0}.box{border:1px solid #ddd;padding:14px;border-radius:12px}</style></head><body><h1>${esc(o.name)}</h1><p>RUT: ${esc(o.rut||"No informado")} · ${esc(o.period||o.year)}</p><div class="tot"><div class="box"><b>Ingresos</b><br>${money(inc.reduce((a,x)=>a+Number(x.amount),0))}</div><div class="box"><b>Egresos</b><br>${money(eg.reduce((a,x)=>a+Number(x.amount),0))}</div><div class="box"><b>Saldo</b><br>${money(inc.reduce((a,x)=>a+Number(x.amount),0)-eg.reduce((a,x)=>a+Number(x.amount),0))}</div></div><table><thead><tr><th>Fecha</th><th>Tipo</th><th>Categoría</th><th>Responsable</th><th>Detalle</th><th>Monto</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${esc(x.date)}</td><td>${esc(x.type)}</td><td>${esc(x.category)}</td><td>${esc(x.responsible)}</td><td>${esc(x.detail)}</td><td>${money(x.amount)}</td></tr>`).join("")}</tbody></table><script>window.onload=()=>setTimeout(()=>window.print(),300)<\/script></body></html>`);w.document.close()}
if("serviceWorker" in navigator) navigator.serviceWorker.register("./sw.js").catch(()=>{});
render();
